config/routes.rb
Rails.application.routes.draw do
  resources :clips
  devise_for :users
  root "home#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/clip.rb
class Clip < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
  before_action :set_clip, only: [:show, :edit, :update, :destroy]

  # GET /clips
  # GET /clips.json
  def index
    @clips = Clip.all
  end

  # GET /clips/1
  # GET /clips/1.json
  def show
  end

  # GET /clips/new
  def new
    @clip = Clip.new
  end

  # GET /clips/1/edit
  def edit
  end

  # POST /clips
  # POST /clips.json
  def create

    begin
      @clip = Clip.new(clip_params)
      page = MetaInspector.new(clip_params[:url])
      @clip.title = page.title
      @clip.discription = page.best_description
      @clip.image = page.images.best
    rescue
      @clip.errors.add(:base, "無効なURLです")
      render :new
      return
    end


    respond_to do |format|
      if @clip.save
        format.html { redirect_to @clip, notice: 'Clip was successfully created.' }
        format.json { render :show, status: :created, location: @clip }
      else
        format.html { render :new }
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clips/1
  # PATCH/PUT /clips/1.json
  def update
    respond_to do |format|
      if @clip.update(clip_params)
        format.html { redirect_to @clip, notice: 'Clip was successfully updated.' }
        format.json { render :show, status: :ok, location: @clip }
      else
        format.html { render :edit }
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clips/1
  # DELETE /clips/1.json
  def destroy
    @clip.destroy
    respond_to do |format|
      format.html { redirect_to clips_url, notice: 'Clip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clip
      @clip = Clip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def clip_params
      params.require(:clip).permit(:url, :title, :discription, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def idnex
     
  end



end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/clips/_form.html.erb
<%= form_with(model: clip, local: true) do |form| %>
  <% if clip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clip.errors.count, "error") %> prohibited this clip from being saved:</h2>

      <ul>
        <% clip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :discription %>
    <%= form.text_area :discription %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clips/edit.html.erb
<h1>Editing Clip</h1>

<%= render 'form', clip: @clip %>

<%= link_to 'Show', @clip %> |
<%= link_to 'Back', clips_path %>

app/views/clips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clips</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Title</th>
      <th>Discription</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clips.each do |clip| %>
      <tr>
        <td><%= clip.url %></td>
        <td><%= clip.title %></td>
        <td><%= clip.discription %></td>
        <td><%= image_tag clip.image, width: 200 %></td>
        <td><%= link_to 'Show', clip %></td>
        <td><%= link_to 'Edit', edit_clip_path(clip) %></td>
        <td><%= link_to 'Destroy', clip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Clip', new_clip_path %>

app/views/clips/new.html.erb
<h1>New Clip</h1>

<%= render 'form', clip: @clip %>

<%= link_to 'Back', clips_path %>

app/views/clips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @clip.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @clip.title %>
</p>

<p>
  <strong>Discription:</strong>
  <%= @clip.discription %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @clip.image, width: 960 %>
</p>

<%= link_to 'Edit', edit_clip_path(@clip) %> |
<%= link_to 'Back', clips_path %>

app/views/home/idnex.html.erb
<h1>Home#idnex</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newsable</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>